version: "3.8"

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_LOCAL_INFILE: "true"
      MYSQL_CLIENT_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/data/db

  front-service:
    container_name: front-service
    build:
      context: ./../front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://192.168.18.199:8080

  back-service:
    container_name: back-service
    build:
      context: ./../back/
      dockerfile: ./../back/back-service.dockerfile
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT_MYSQL: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1

volumes:
  db_data:
